FROM docker.io/owncloud/base:20.04@sha256:0ba0c139b6d3437997642aa593106cc2047b6349b9b351fe61d2dc2d0d34fa1e

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud Univention Appliance" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/appliance" \
  org.opencontainers.image.source="https://github.com/owncloud-docker/appliance" \
  org.opencontainers.image.documentation="https://github.com/owncloud-docker/appliance"

VOLUME ["/mnt/data"]
EXPOSE 8080

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/owncloud", "server"]

ADD owncloud.tar.bz2 /var/www/
ADD user_ldap.tar.gz /var/www/owncloud/apps/
ADD richdocuments.tar.gz /var/www/owncloud/apps/
ADD onlyoffice.tar.gz /var/www/owncloud/apps/
ADD openidconnect.tar.gz /var/www/owncloud/apps/

ADD overlay /
WORKDIR /var/www/owncloud

RUN find /var/www/owncloud \( \! -user www-data -o \! -group root \) -print0 | xargs -r -0 chown www-data:root && \
  chmod g+w /var/www/owncloud
