FROM owncloud/base:20.04-amd64@sha256:0bba7e8633b999cb35fd8b3ced7540636f6d7979f8587664065f32c580c71ee1

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud Univention Appliance" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/appliance" \
  org.opencontainers.image.source="https://github.com/owncloud-docker/appliance" \
  org.opencontainers.image.documentation="https://github.com/owncloud-docker/appliance"

VOLUME ["/mnt/data"]
EXPOSE 8080

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/owncloud", "server"]

ADD owncloud.tar.bz2 /var/www/
ADD user_ldap.tar.gz /var/www/owncloud/apps/
ADD richdocuments.tar.gz /var/www/owncloud/apps/
ADD onlyoffice.tar.gz /var/www/owncloud/apps/
ADD openidconnect.tar.gz /var/www/owncloud/apps/

ADD overlay /
WORKDIR /var/www/owncloud

RUN find /var/www/owncloud \( \! -user www-data -o \! -group root \) -print0 | xargs -r -0 chown www-data:root && \
  chmod g+w /var/www/owncloud
