workspace:
  base: /drone
  path: src/github.com/owncloud-docker/appliance

branches:
  - master

clone:
  git:
    image: plugins/git:1
    pull: true

pipeline:
  tarball:
    image: plugins/download:1
    pull: true
    secrets: [ download_username, download_password ]
    source: https://download.owncloud.org/community/owncloud-10.3.0.tar.bz2
    sha256: 3fc96799af93e10f1228970371668c83d8c07a3fdca67369105e56420ff36e64

  ldap:
    image: plugins/download:1
    pull: true
    source: https://marketplace.owncloud.com/api/v1/apps/user_ldap/0.13.0
    sha256: f35042d11df9c26d22af44dba600efa3b7d134bf93294923ebd8c5fd506a65b3
    destination: user_ldap.tar.gz

  richdocuments:
    image: plugins/download:1
    pull: true
    source: https://marketplace.owncloud.com/api/v1/apps/richdocuments/2.1.2
    sha256: 28f9903653f3191146f838a70293afa99ac203a2a64db98ba1fb2e7adef43a9f
    destination: richdocuments.tar.gz

  onlyoffice:
    image: plugins/download:1
    pull: true
    source: https://marketplace.owncloud.com/api/v1/apps/onlyoffice/3.0.3
    sha256: bc99c5ed74ab9fa95dedbbc791855dce4fba8d83704c8dc53f1a6d7e2f4c80d0
    destination: onlyoffice.tar.gz

  wait:
    image: owncloud/ubuntu:latest
    pull: true
    commands:
      - wait-for-it -t 600 docker:2375

  build:
    image: toolhippie/docker:latest
    pull: true
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker build -t owncloud/appliance:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER} .

  server:
    image: toolhippie/docker:latest
    pull: true
    detach: true
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker run -p 8000:8080 owncloud/appliance:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}

  test:
    image: owncloud/ubuntu:latest
    pull: true
    commands:
      - wait-for-it -t 600 docker:8000
      - curl -sSf http://docker:8000/status.php

  prepublish:
    image: toolhippie/docker:latest
    pull: true
    secrets: [ docker_username, docker_password ]
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - docker push owncloud/appliance:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}
    when:
      event: [ push, pull_request ]

  clair:
    image: toolhippie/klar:latest
    pull: true
    secrets:
      - source: docker_username
        target: docker_user
      - source: docker_password
        target: docker_password
    environment:
      - CLAIR_ADDR=clair.owncloud.com
      - CLAIR_OUTPUT=High
    commands:
      - klar owncloud/appliance:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}
    when:
      event: [ push, pull_request ]

  publish:
    image: toolhippie/docker:latest
    pull: true
    secrets: [ docker_username, docker_password ]
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - docker tag owncloud/appliance:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER} owncloud/appliance:latest
      - docker push owncloud/appliance:latest
      - docker tag owncloud/appliance:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER} owncloud/appliance:latest-$(date '+%Y%m%d')
      - docker push owncloud/appliance:latest-$(date '+%Y%m%d')
      - docker tag owncloud/appliance:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER} owncloud/appliance:10.3.0
      - docker push owncloud/appliance:10.3.0
      - docker tag owncloud/appliance:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER} owncloud/appliance:10.3.0-$(date '+%Y%m%d')
      - docker push owncloud/appliance:10.3.0-$(date '+%Y%m%d')
      - docker tag owncloud/appliance:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER} owncloud/appliance:10.3
      - docker push owncloud/appliance:10.3
    when:
      event: [ push ]

  cleanup:
    image: toolhippie/jq:latest
    pull: true
    secrets: [ docker_username, docker_password ]
    commands:
      - |
        TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'"$DOCKER_USERNAME"'", "password": "'"$DOCKER_PASSWORD"'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
        curl -sSf -o /dev/null -H "Authorization: JWT $TOKEN" -H "Content-Type: application/json" -X DELETE https://hub.docker.com/v2/repositories/owncloud/appliance/tags/${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}/
    when:
      event: [ push, pull_request ]
      status: [ success, failure ]

  microbadger:
    image: plugins/webhook:1
    pull: true
    secrets: [ webhook_urls ]
    when:
      local: false
      event: [ push ]

  slack:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: docker
    when:
      local: false
      event: [ push ]
      status: [ changed, failure ]

services:
  docker:
    image: docker:18.04-dind
