workspace:
  base: /drone
  path: src/github.com/owncloud-docker/appliance

branches:
  - master

clone:
  git:
    image: plugins/git:1
    pull: true

pipeline:
  tarball:
    image: plugins/download:1
    pull: true
    secrets: [ download_username, download_password ]
    source: https://download.owncloud.org/community/owncloud-${CORE_VERSION}.tar.bz2
    sha256: ${CORE_CHECKSUM}

  ldap:
    image: plugins/download:1
    pull: true
    source: https://github.com/owncloud/user_ldap/releases/download/${LDAP_VERSION}/user_ldap.tar.gz
    sha256: ${LDAP_CHECKSUM}

  richdocuments:
    image: plugins/download:1
    pull: true
    source: https://github.com/owncloud/richdocuments/releases/download/${RICHDOCUMENTS_VERSION}/richdocuments.tar.gz
    sha256: ${RICHDOCUMENTS_CHECKSUM}

  onlyoffice:
    image: plugins/download:1
    pull: true
    source: https://github.com/ONLYOFFICE/onlyoffice-owncloud/releases/download/${ONLYOFFICE_VERSION}/onlyoffice-owncloud.tar.gz
    sha256: ${ONLYOFFICE_CHECKSUM}

  wait:
    image: owncloud/ubuntu:latest
    pull: true
    commands:
      - wait-for-it -t 600 docker:2375

  build:
    image: toolhippie/docker:latest
    pull: true
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker build -t owncloud/appliance:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}-${DRONE_JOB_NUMBER} .

  server:
    image: toolhippie/docker:latest
    pull: true
    detach: true
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker run -p 8000:80 owncloud/appliance:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}-${DRONE_JOB_NUMBER}

  test:
    image: owncloud/ubuntu:latest
    pull: true
    commands:
      - wait-for-it -t 600 docker:8000
      - curl -sSf http://docker:8000/status.php

  prepublish:
    image: toolhippie/docker:latest
    pull: true
    secrets: [ docker_username, docker_password ]
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - docker push owncloud/appliance:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}-${DRONE_JOB_NUMBER}
    when:
      event: [ push, pull_request ]

  clair:
    image: toolhippie/klar:latest
    pull: true
    secrets:
      - source: docker_username
        target: docker_user
      - source: docker_password
        target: docker_password
    environment:
      - CLAIR_ADDR=clair.owncloud.com
      - CLAIR_OUTPUT=High
    commands:
      - klar owncloud/appliance:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}-${DRONE_JOB_NUMBER}
    when:
      event: [ push, pull_request ]

  publish:
    image: toolhippie/docker:latest
    pull: true
    secrets: [ docker_username, docker_password ]
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - |
        for IMAGE in ${IMAGE_TAGS}; do
          docker tag owncloud/appliance:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}-${DRONE_JOB_NUMBER} owncloud/appliance:$IMAGE
          docker push owncloud/appliance:$IMAGE
        done
    when:
      event: [ push ]

  cleanup:
    image: toolhippie/jq:latest
    pull: true
    secrets: [ docker_username, docker_password ]
    commands:
      - |
        TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'"$DOCKER_USERNAME"'", "password": "'"$DOCKER_PASSWORD"'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
        curl -sSf -o /dev/null -H "Authorization: JWT $TOKEN" -H "Content-Type: application/json" -X DELETE https://hub.docker.com/v2/repositories/owncloud/appliance/tags/${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}-${DRONE_JOB_NUMBER}/
    when:
      event: [ push, pull_request ]
      status: [ success, failure ]

  microbadger:
    image: plugins/webhook:1
    pull: true
    secrets: [ webhook_urls ]
    when:
      local: false
      event: [ push ]

  slack:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: docker
    when:
      local: false
      event: [ push ]
      status: [ changed, failure ]

services:
  docker:
    image: docker:18.04-dind

matrix:
  include:
    - CORE_VERSION: 10.0.9
      CORE_CHECKSUM: 767faedf7b236b469e71ad73a70c6250fc33fd493708d95cf31b0b58b4710973
      RICHDOCUMENTS_VERSION: 2.0.6
      RICHDOCUMENTS_CHECKSUM: dbca97f24abecb10a23686361e56a1c91c24d9007a5c142169c75a836b8cebed
      LDAP_VERSION: v0.11.0
      LDAP_CHECKSUM: f89b4ea5b519f30b2ceefca2cca82af5f961dc04c29dea2a7c477b1d11f1c303
      ONLYOFFICE_VERSION: v1.3.0
      ONLYOFFICE_CHECKSUM: 4690a6c53f4f2b7dd22355f35dca142280c0030cf417cca762581f11eed35ae9
      IMAGE_TAGS: 10.0.9 10.0 latest
    - CORE_VERSION: 10.0.8
      CORE_CHECKSUM: 9eef77a171cf69fc89b0628b083b4b1dd15eec375599c7eb5ac0b6d37ab6f903
      RICHDOCUMENTS_VERSION: 2.0.6
      RICHDOCUMENTS_CHECKSUM: dbca97f24abecb10a23686361e56a1c91c24d9007a5c142169c75a836b8cebed
      LDAP_VERSION: v0.11.0
      LDAP_CHECKSUM: f89b4ea5b519f30b2ceefca2cca82af5f961dc04c29dea2a7c477b1d11f1c303
      ONLYOFFICE_VERSION: v1.3.0
      ONLYOFFICE_CHECKSUM: 4690a6c53f4f2b7dd22355f35dca142280c0030cf417cca762581f11eed35ae9
      IMAGE_TAGS: 10.0.8
